project:
  type: website
  output-dir: docs

website:
  title: "project-template"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Data import"
        file: data-import.qmd
      - text: "Quick example"
        file: quick-ex.qmd
    right:
      - icon: github
        href: https://github.com/EBGC-group/

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

